image: Visual Studio 2017

build_script:
  - .\.build\configure_win_static.bat
  - .\.build\make.bat
  - .\.build\make_install.bat
  - .\.test00\build.bat
  - .\.test00\run.bat


after_build:
  - 7z a artifacts.7z C:\Qt\Qt-5.11.1\


artifacts:
  - path: artifacts.7z


on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

